name: ISPChecker
version: 0.1.0.0
github: "githubuser/ISPChecker"
license: BSD-3-Clause
author: "Author name here"
maintainer: "example@example.com"
copyright: "2024 Author name here"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/ISPChecker#readme>

dependencies:
  - base >= 4.7 && < 5
  - containers >= 0.6.7
  - megaparsec >= 9.0
  - text >= 2.0 && < 2.1
  - mtl >= 2.3.1
  - pretty-show

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints.md

library:
  source-dirs: src
  default-extensions:
    - NoFieldSelectors
    - RecordWildCards
    - DuplicateRecordFields
    - FlexibleInstances
    - OverloadedStrings
    - OverloadedRecordDot
    - NamedFieldPuns

executables:
  ISPChecker-exe:
    main: Main.hs
    source-dirs: app
    default-extensions:
      - NoFieldSelectors
      - RecordWildCards
      - DuplicateRecordFields
      - FlexibleInstances
      - OverloadedStrings
      - OverloadedRecordDot
      - NamedFieldPuns
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - ISPChecker

tests:
  ISPChecker-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - ISPChecker
